### ISSUE TITLE
Throwing a written book into the portal results in a crash

### ISSUE THREAD

**Issue by tylerb153** [LeraRiemann/ProjectInfinity#26]
When throwing a book into the portal if the book contains no text inside the game crashes. I am using the current latest version and fabric loader 0.15.11. Below is the error that the crash report states. I tried changing the "Salt" value and it happens as well. This crash results in the world being inaccessible. 

Description: Colliding entity with block

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at net.minecraft.class_2499.method_10534(class_2499.java:274)
	at net.lerariemann.infinity.var.ModCommands.getDimensionSeed(ModCommands.java:66)
	at net.minecraft.class_2423.handler$zlm000$infinity$injected(class_2423.java:536)
	at net.minecraft.class_2423.method_9548(class_2423.java)
	at net.lerariemann.infinity.block.custom.NeitherPortalBlock.method_9548(NeitherPortalBlock.java:248)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:1121)
	at net.minecraft.class_1297.method_5852(class_1297.java:1137)
	at net.minecraft.class_1297.method_36974(class_1297.java:851)
	at net.minecraft.class_1297.method_5784(class_1297.java:799)
	at net.minecraft.class_1542.method_5773(class_1542.java:136)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by cassiancc** [comment]
Fixed in https://github.com/LeraRiemann/ProjectInfinity/pull/21, as the mod tries to read the book's text even if there's no text present.

**Comment by Tim-Magee** [comment]
Came here to report two issues, only to find they're already fixed in this PR. Nice one!
