### ISSUE TITLE
[Server] [1.20.1] [Fabric] Server crashes on "ticking block entity" on player join

### ISSUE THREAD

**Issue by slomas04** [LeraRiemann/ProjectInfinity#45]
As the title suggests, the server crashes when a player joins, the error message states an error in "Ticking block entity" originating from a NoSuchFileException

Full crash logs:
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-09-30 19:50:38
Description: Ticking block entity

java.lang.RuntimeException: java.nio.file.NoSuchFileException: config\infinity\modular\bro\surface_rule\saturated\cave\bone_cavern.json
	at net.lerariemann.infinity.util.CommonIO.write(CommonIO.java:51)
	at net.lerariemann.infinity.util.CommonIO.writeSurfaceRule(CommonIO.java:40)
	at net.lerariemann.infinity.util.SurfaceRuleScanner.lambda$scan$4(SurfaceRuleScanner.java:35)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at net.lerariemann.infinity.util.SurfaceRuleScanner.scan(SurfaceRuleScanner.java:31)
	at net.lerariemann.infinity.util.ConfigGenerator.generateAll(ConfigGenerator.java:255)
	at net.lerariemann.infinity.block.entity.CosmicAltarEntity.serverTick(CosmicAltarEntity.java:48)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.nio.file.NoSuchFileException: config\infinity\modular\bro\surface_rule\saturated\cave\bone_cavern.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:227)
	at java.base/java.nio.file.Files.write(Files.java:3561)
	at net.lerariemann.infinity.util.CommonIO.write(CommonIO.java:49)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.lerariemann.infinity.util.CommonIO.write(CommonIO.java:51)
	at net.lerariemann.infinity.util.CommonIO.writeSurfaceRule(CommonIO.java:40)
	at net.lerariemann.infinity.util.SurfaceRuleScanner.lambda$scan$4(SurfaceRuleScanner.java:35)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at net.lerariemann.infinity.util.SurfaceRuleScanner.scan(SurfaceRuleScanner.java:31)
	at net.lerariemann.infinity.util.ConfigGenerator.generateAll(ConfigGenerator.java:255)
	at net.lerariemann.infinity.block.entity.CosmicAltarEntity.serverTick(CosmicAltarEntity.java:48)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: infinity:cosmic_block_entity // net.lerariemann.infinity.block.entity.CosmicAltarEntity
	Block: Block{infinity:altar_cosmic}
	Block location: World: (-3231,310,63), Section: (at 1,6,15 in -202,19,3; chunk contains blocks -3232,-64,48 to -3217,319,63), Region: (-7,0; contains chunks -224,0 to -193,31, blocks -3584,-64,0 to -3073,319,511)
	Block: Block{infinity:altar_cosmic}
	Block location: World: (-3231,310,63), Section: (at 1,6,15 in -202,19,3; chunk contains blocks -3232,-64,48 to -3217,319,63), Region: (-7,0; contains chunks -224,0 to -193,31, blocks -3584,-64,0 to -3073,319,511)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Slomas99'/75, l='ServerLevel[world]', x=-3230.02, y=63.00, z=1.98]]
	Chunk stats: 3294
	Level dimension: minecraft:overworld
	Level spawn location: World: (-523,175,-120), Section: (at 5,15,8 in -33,10,-8; chunk contains blocks -528,-64,-128 to -513,319,-113), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 11113985 game time, 639216 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 36242 (now: false), thunder time: 28937 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1844397648 bytes (1758 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24c9
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6094
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36795.70
	Virtual memory used (MB): 26670.93
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 1482.65
	JVM Flags: 20 total; -Xms4096M -Xmx4096M -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+PerfDisableSharedMem -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1HeapRegionSize=8M -XX:G1HeapWastePercent=5 -XX:G1MaxNewSizePercent=40 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1NewSizePercent=30 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -XX:MaxGCPauseMillis=200 -XX:MaxTenuringThreshold=1 -XX:SurvivorRatio=32
	Fabric Mods: 
		ad_astra: Ad Astra 1.15.18
			javazoom_jlayer: jlayer 1.0.1
		additionalstructures: Additional Structures 4.2.2
		adorn: Adorn 5.0.1+1.20.1
		ae2: Applied Energistics 2 15.2.12
			team_reborn_energy: Energy 3.0.0
		amendments: Amendments 1.20-1.2.11
		animal_feeding_trough: Animal Feeding Trough 1.1.0+1.20.1
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		archers: Archers (RPG Series) 1.2.5+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
			structure_pool_api: Structure Pool API 1.0+1.20.1
		architectury: Architectury 9.2.14
		azurelib: AzureLib 2.0.35
		azurelibarmor: AzureLib Armor 2.0.8
		badpackets: Bad Packets 0.4.3
		balm-fabric: Balm 7.3.9
			kuma_api: KumaAPI 20.1.8
		bbb: Building But Better 1.20.1-fabric-1.0.2
		beachparty: [Let's Do] Beachparty 1.1.5
		beautify: Beautify 1.2.0+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		biomeswevegone: Oh The Biomes We've Gone 1.2.3
		botarium: Botarium 2.3.4
		candlelight: [Let's Do] Candlelight 1.2.13
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chunky: Chunky 1.3.146
		cicada: CICADA 0.8.3+1.20.1
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		collective: Collective 7.84
		combatroll: Combat Roll 1.3.3+1.20.1
		comforts: Comforts 6.4.0+1.20.1
		compressedblocks: Compressed Blocks 1.13
		corgilib: CorgiLib 4.0.3.2
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		createaddition: Create Crafts & Additions 1.2.4
		createbigcannons: Create Big Cannons 5.5.1+mc.1.20.1-fabric
			ritchiesprojectilelib: Ritchie's Projectile Library 2.0.0-dev+mc.1.20.1-fabric-build.182
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		createdeco: Create Deco 2.0.2-1.20.1-fabric
		creategoggles: Create Goggles 0.5.5.g
		creeperoverhaul: Creeper Overhaul 3.0.2
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.4.7
		darkwaters: Dark Waters 0.0.22
		distantfriends: Distant Friends 0.5.4
		do_a_barrel_roll: Do a Barrel Roll 3.6.1+1.20.1
			mixinsquared: MixinSquared 0.1.1
		doapi: [Let's Do] API 1.2.15
		dungeons_arise: When Dungeons Arise 2.1.57
		effortless: Effortless Structure 3.1.0
		eldritch_end: Eldritch End 0.3.0
			aaa_particles: AAAParticles 1.20.1-1.2.1
		emotecraft: Emotecraft 2.2.7-b.build.50
		entityculling: EntityCulling 1.7.0
		evs: Enchanted Vertical Slabs 2.2.1-backport1.20.1
		explorify: Explorify 1.6.2
		extended_drawers: Extended Drawers 2.1.1+mc.1.20.1
			config_toolkit: ConfigToolkit 1.0.0
				io_determann_shadow-api-17: shadow-api-17 0.1.1
				net_fabricmc_javapoet: javapoet 0.1.0
			graphlib: Graph Lib 1.4.0+1.20
				libnetworkstack: Lib Network Stack 0.10.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.20.1-2.1.6+refabricated
			mm: Manningham Mills 2.3
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
		ferritecore: FerriteCore 6.0.1
		friendsandfoes: Friends&Foes 2.0.17
		geckolib: GeckoLib 4 4.4.9
			com_eliotlash_mclib_mclib: mclib 20
		handcrafted: Handcrafted 3.0.6
		hearth_and_home: Hearth & Home 1.20.1-2.0.3
		herobrine: The Legend of Herobrine 0.7.2
		image2map: Image2Map 0.4.2+1.20
			map-canvas-api: Map Canvas API 0.2.2+1.19.4
			sgui: sgui 1.2.2+1.20
		immersive_aircraft: Immersive Aircraft 1.1.2+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		immersive_armors: Immersive Armors 1.6.1+1.20.1
		infinity: Infinite Dimensions 1.20.1 1.11.1-1.20.1
		java: Java HotSpot(TM) 64-Bit Server VM 21
		joinleavemessages: Joinleavemessages fabric-1.19.3-2.0.0
			com_networkglitch_common_: common 1.0.0
		keybind_fix: Keybind Fix 1.0.0
		kubejs: KubeJS 2001.6.5-build.14
		lithium: Lithium 0.11.2
		lithostitched: Lithostitched 1.1.8
		lootr: Lootr 0.7.33.81
		man_of_many_planes: Man of Many Planes 0.2.0+1.20.1
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		moonlight: Moonlight 1.20-2.12.21
		moremobvariants: More Mob Variants 1.3.1
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3.f
		mr_saturated: Saturated 0.12-2
		naturalist: Naturalist 4.0.3
		necronomicon: Necronomicon 1.4.2
		nightlights: Night Lights 1.1
		notenoughanimations: NotEnoughAnimations 1.7.6
		nutritionz: NutritionZ 1.0.10
		oceansdelight: Ocean's Delight fdrf-fabric-1.0.2-1.20
		ohthetreesyoullgrow: Oh The Trees You'll Grow 1.20.1-1.3.0
		openpartiesandclaims: Open Parties and Claims 0.23.2
		oreharvester: Ore Harvester 1.4
		paladins: Paladins & Priests (RPG Series) 1.3.1+1.20.1
			shield_api: Shield API 1.0.0+1.20.1
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.6+1.20.1
			spectrelib: SpectreLib 0.13.16+1.20.1
				com_electronwill_night-config_core: core 3.8.1
				com_electronwill_night-config_toml: toml 3.8.1
		puzzleslib: Puzzles Lib 8.1.23
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		quarrymod: Industrial Quarry Mod 1.2.0
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.20.1
		ranged_weapon_api: RangedWeaponAPI 1.1.4+1.20.1
		reborncore: Reborn Core 5.8.7
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.29
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		rhino: Rhino 2001.2.3-build.6
		roughlyenoughitems: Roughly Enough Items 12.1.758
			error_notifier: Error Notifier 1.0.9
		runes: Runes 0.9.13+1.20.1
		servercore: ServerCore 1.5.1+1.20.1
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			org_yaml_snakeyaml: snakeyaml 2.2
			placeholder-api: Placeholder API 2.1.3+1.20.1
			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2
			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.11.0-pre.2
			libblockattributes: LibBlockAttributes 0.14.0-pre.1
				libblockattributes_core: LibBlockAttributes (Core) 0.14.0-pre.1
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.14.0-pre.1
				libblockattributes_items: LibBlockAttributes (Items) 0.14.0-pre.1
			libmultipart: LibMultiPart 0.11.0-pre.2
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.11.0-pre.2
			simple_pipes: SimplePipeTest 0.11.0-pre.2
		simplyswords: Simply Swords 1.56.0-1.20.1
		sliceanddice: Create Slice & Dice 3.2.3
		smartbrainlib: SmartBrainLib 1.15
		spark: spark 1.10.53
		spell_engine: Spell Engine 0.15.10+1.20.1
		spell_power: Spell Power Attribute 0.12.0+1.20.1
		styledplayerlist: Styled Player List 3.1.1+1.20.1
			player-data-api: Player Data API 0.2.2+1.19.3
			predicate-api: Predicate API 0.1.2+1.20
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supplementaries: Supplementaries 1.20-2.8.17
		suppsquared: Supplementaries Squared 1.20-1.1.15
		t_and_t: Towns and Towers 1.12
		techreborn: Tech Reborn 5.8.7
		tectonic: Tectonic 2.4.1b
		terrablender: TerraBlender 3.0.1.7
		terralith: Terralith 2.5.4
		terrestria: Terrestria 6.0.13
			biolith: Biolith 1.0.0-beta.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.3
			terraform-config-api-v1: Terraform Config API (v1) 7.0.3
			terraform-dirt-api-v1: Terraform Dirt API (v1) 7.0.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.3
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.3
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
			terrestria-common: Terrestria: Common 6.0.13
			terrestria-worldgen: Terrestria: World Generation 6.0.13
		the_bumblezone: The Bumblezone - Fabric 7.4.18+1.20.1-fabric
			athena: Athena 3.1.1
		tlc: The Lost Castle 1.0.1
		travelersbackpack: Traveler's Backpack fabric-1.20.1-9.1.16
		treeharvester: Tree Harvester 9.1
		villagernames: Villager Names 8.1
		vinery: [Let's Do] Vinery 1.4.28
		visualworkbench: Visual Workbench 8.0.0
		watching: From The Fog 1.9.2
		waystones: Waystones 14.1.5
		wizards: Wizards (RPG Series) 1.3.0+1.20.1
		wthit: wthit 8.15.2
		xaerominimap: Xaero's Minimap 24.4.0
		xaeroworldmap: Xaero's World Map 1.39.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yigd: You're in Grave Danger 2.0.6
			libgui: LibGui 8.1.1+1.20.1
				jankson: Jankson 6.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Server Running: true
	Player Count: 1 / 20; [class_3222['Slomas99'/75, l='ServerLevel[world]', x=-3230.02, y=63.00, z=1.98]]
	Data Packs: vanilla, Suppsquared Generated Pack, Supplementaries Generated Pack, fabric, resources/t_and_t_waystones_patch_1.19.2 (incompatible), tectonic/terratonic, nutritionz:farmersdelight_nutrition_compat, nutritionz:candlelight_nutrition_compat, nutritionz:adastra_nutrition_compat, nutritionz:oceansdelight_nutrition_compat, nutritionz:naturalist_nutrition_compat, nutritionz:vinery_nutrition_compat, nutritionz:create_nutrition_compat, nutritionz:supplementaries_nutrition_compat, nutritionz:thebumblezone_nutrition_compat, nutritionz:createaddition_nutrition_compat, nutritionz:beachparty_nutrition_compat
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by slomas04** [comment]
All good! I may put a PR through for 1.20 if I have the time.

**Comment by LeraRiemann** [comment]
aaand done for .21 in the latest commit :3
