### ISSUE TITLE
Crash on Fabric 1.20.1 (Loader 0.15.6)

### ISSUE THREAD

**Issue by ErkedScreeN** [LeraRiemann/ProjectInfinity#6]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-02-14 02:31:37
Description: Starting integrated server

java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
	at net.lerariemann.**infinity.dimensions**.RandomProvider.rule(RandomProvider.java:129)
	at net.lerariemann.infinity.var.ModCommands.getDimensionSeed(ModCommands.java:45)
	at net.lerariemann.infinity.var.ModCommands.getDimensionSeedFromText(ModCommands.java:41)
	at net.lerariemann.**infinity.dimensions**.Easterizer.<init>(Easterizer.java:21)
	at net.lerariemann.**infinity.dimensions**.RandomProvider.<init>(RandomProvider.java:44)
	at net.minecraft.server.MinecraftServer.handler$dpp000$infinity$injected(MinecraftServer.java:7857)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:304)
	at net.minecraft.class_1132.<init>(class_1132.java:50)
	at net.minecraft.class_310.method_29603(class_310.java:2094)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:272)
	at net.minecraft.class_310.method_29610(class_310.java:2094)
	at net.minecraft.class_7196.method_43326(class_7196.java:235)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:233)
	at net.minecraft.class_7196.method_41894(class_7196.java:64)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402)
	at net.minecraft.class_350.method_25402(class_350.java:327)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at dynamic_fps.impl.util.event.InputObserver.onPress(InputObserver.java:96)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.lerariemann.**infinity.dimensions**.RandomProvider.rule(RandomProvider.java:129)
	at net.lerariemann.infinity.var.ModCommands.getDimensionSeed(ModCommands.java:45)
	at net.lerariemann.infinity.var.ModCommands.getDimensionSeedFromText(ModCommands.java:41)
	at net.lerariemann.**infinity.dimensions**.Easterizer.<init>(Easterizer.java:21)
	at net.lerariemann.**infinity.dimensions**.RandomProvider.<init>(RandomProvider.java:44)
	at net.minecraft.server.MinecraftServer.handler$dpp000$infinity$injected(MinecraftServer.java:7857)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:304)
	at net.minecraft.class_1132.<init>(class_1132.java:50)
	at net.minecraft.class_310.method_29603(class_310.java:2094)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:272)
	at net.minecraft.class_310.method_29610(class_310.java:2094)
	at net.minecraft.class_7196.method_43326(class_7196.java:235)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:233)
	at net.minecraft.class_7196.method_41894(class_7196.java:64)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402)
	at net.minecraft.class_350.method_25402(class_350.java:327)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at dynamic_fps.impl.util.event.InputObserver.onPress(InputObserver.java:96)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)

-- Starting integrated server --
Details:
	Level ID: surv2023
	Level Name: surv2023
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2094)
	at net.minecraft.class_7196.method_43326(class_7196.java:235)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:233)
	at net.minecraft.class_7196.method_41894(class_7196.java:64)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:402)
	at net.minecraft.class_350.method_25402(class_350.java:327)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at dynamic_fps.impl.util.event.InputObserver.onPress(InputObserver.java:96)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by LeraRiemann** [comment]
looks like you updated the mod without purging the config. doing so (deleting the config/infinity folder and restarting the game) should fix the issue.
